services:
  - type: web
    name: daily-question-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_APP_TOKEN
        sync: false
      - key: SLACK_CHANNEL_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: QUESTION_TIME
        value: "9:00"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SIMILARITY_THRESHOLD
        value: "0.85"
      - key: EMBEDDING_MODEL
        value: "text-embedding-3-small"
      - key: MIN_QUESTIONS_FOR_CHECK
        value: "5" 